server:
  port: 8769
  contextPath: /auth

jdbc:
  type: mysql

mybatis:
  mapperLocations: classpath:mapper/*.xml
  configLocation: classpath:/mybatis-config.xml
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

spring:
  application:
      name: auth-service
# 数据源
  datasource:
      name: test
      url: jdbc:mysql://101.226.164.132:3306/auth?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root123456
      type: com.alibaba.druid.pool.DruidDataSource #使用drudi数据源
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat,wall,log4j
      maxActive: 200
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
# redis
  redis:
    database: 2
    host: 101.226.164.132:3306
    port: 6699
    password: QV@lPRnuaKrX$RAvewLtcD0EOD$&ND7*ZOb57eUZB5G&k$^2Eju%l$$8Ta4TPbcj@8S#yTP6h%UGqs7&X!n26PkmYRVFzPo%e0ODNYXh*Kbo##U8H!w!r6ycewdfowL!40qq*9L5G*no7z@rjUZk#AaQAi9ybciZ^C!2fplS7hYxqd9P1Td4hmAFZVR^#BLgNXK0v0rimP3P%7rPMoNFb@L%fVXHE^kvxIkBgHUAAG8Yb9NqMMJ0oofXj0qlR2QmV0na*gs@x*#IOplLs4@Eq%nvS*DI3c4lFd9g*OS9T
    pool:
      max-active: 1000
      max-wait: 1000
      max-idle: 1000
      min-idle: 0
    timeout: 0

# spring security oauth2 配置
security:
#  sessions: if-required
  basic:
    enabled: false
  oauth2:
    resource:
      jwt:
        keyValue: |
           -----BEGIN PUBLIC KEY-----
           MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAimUKhvBhsoeSM3HkIOP/Y3RXjvonBlZnLj8oO92TyAKG53lmAoK0wZ5MTZPsfrOz2Z7CeAp6mPhUANX2RUoFwVzG7rJmgWyqGmGFNBmtYL+uVqQ80TzWi5zyzXTxgVMWiCqqw/u4AeE1qhN8chnGwhUBnpgPAPd8v57mIwg0n5JxjdYe7pgHlpvt8ZXTXd1KBxB5K7WjNlCfMf75ZEeBaplxsSfJUwKbnHQKWcY3NnpjkVR8y4jviAbkOHmGMaliM7fcsLzbosBUPDQuNlvYdjPBRfH6MMPeXRW6On3u0Um9wIYmkQS+AEgHCq4UuLOnTTqqxnGkwFYeMAAXmRyMtQIDAQAB
           -----END PUBLIC KEY-----

#logback配置，开发模式日志级别为 INFO
logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
    com:
      tangyi:
        mapper: TRACE

