spring:
  profiles: development
  application:
    name: exam-service
# 数据源
  datasource:
      name: test
      url: jdbc:mysql://101.226.164.132:3306/exam?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root123456
      type: com.alibaba.druid.pool.DruidDataSource #使用drudi数据源
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat,wall,log4j
      maxActive: 200
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
# redis
  redis:
    database: 2
    host: 101.226.164.132
    port: 6379
    password:
    pool:
      max-active: 1000
      max-wait: 1000
      max-idle: 1000
      min-idle: 0
    timeout: 1000

mybatis:
  mapperLocations: classpath:mapper/*.xml
  configLocation: classpath:/mybatis-config.xml
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# 配置运行端口号
server:
  port: 8870

# 注册中心配置
eureka:
  instance:
      hostname: localhost
      port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

# 禁用 security 基本配置
security:
  basic:
    enabled: false

#logback配置，开发模式日志级别为 INFO
logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
    com:
      tangyi:
        mapper: TRACE
